feat: persisting open files on refresh/reload
haxzie/snipp.in pull request #8
Opened 2020-10-19 21:37 UTC by ChoukseyKhushbu

Fixes issue #7

2020-10-20 13:03 UTC, haxzie commented
Hey @ChoukseyKhushbu, good job with the PR :+1: 

A couple of changes that I think might be good.
1. Rename `openFileFooter.model.js` to `openFileFootprint.model.js`
2. While closing a file, check if the file is active, or check if it exists in the `db.activeFiles` and emove the file from `db.activeFiles`.

Rest everything looks good to me :+1:

2020-10-20 13:05 UTC, haxzie requested changes

2020-10-20 13:05 UTC, haxzie commented on src/models/openFileFooter.model.js
> +export default class OpenFileFootprint {
It'd be great if the filename matched the classname

2020-10-20 17:40 UTC, ChoukseyKhushbu commented
I have implemented the requested changes. Please review @haxzie. Thanks :)

2020-10-26 14:29 UTC, haxzie approved these changes

2020-10-26 14:30 UTC, haxzie commented
Good job @ChoukseyKhushbu :+1:  Thanks for the PR :partying_face:

2020-10-26 14:30 UTC, closed without merging